// GENERATED by scripts/terminal-data.mjs from real captured runs. Do not edit by hand.
export const TERM = {
  "recordedAt": "2026-09-16T09:10:11.803Z",
  "header": [
    "DEMO: what happens when the network drops after the money is sent",
    "Base Sepolia | AgentKit account 0x292D5dcdb6aC1F3a0452E6eB8fA26Ff6658B325d | KeeperHub wallet 0x449FE01435Af28FD60320B198219068d3f1656CB"
  ],
  "part1": [
    "[1] The agent sends money. The confirmation never comes back.",
    "Error transferring the asset: InvalidInputRpcError: Missing or invalid parameters.",
    "Double check you have provided the correct parameters.",
    "[2] The error text above is all the agent receives.",
    "    No executionId. No way to ask again.",
    "    The agent does not know whether the money left.",
    "[3] The agent does the reasonable thing: it retries.",
    "Error transferring the asset: InvalidInputRpcError: Missing or invalid parameters.",
    "Double check you have provided the correct parameters.",
    "RESULT: 2 transfers landed for ONE job.",
    "  0xac2b2d8f318829de04173df84d291cab652bbfb2eb30c42a8136a22782f24114",
    "  0x0e961700e867513befb50787b9f06a1e39fbf66317d937af5b990537639b54c4",
    "  ^ the money left twice."
  ],
  "part2": [
    "[1] The agent sends money through KeeperHub.",
    "Transfer handed to KeeperHub.",
    "executionId: ok75dk43ushogcorut9i9",
    "status: completed",
    "transactionHash: 0x0684e7df191193de1cc4684fe8a8d358f9daae98a1a3f2e0281c11a02d92d3fd",
    "explorer: https://sepolia.basescan.org/tx/0x0684e7df191193de1cc4684fe8a8d358f9daae98a1a3f2e0281c11a02d92d3fd",
    "taskId: demo-1789549786787",
    "Keep both. If anything fails after this point, call get_execution_status with the executionId, or call transfer again with the same taskId to get the executionId back. Do not use a new taskId.",
    "[2] The agent retries the same job, exactly as before.",
    "Transfer handed to KeeperHub.",
    "executionId: ok75dk43ushogcorut9i9",
    "status: completed",
    "transactionHash: 0x0684e7df191193de1cc4684fe8a8d358f9daae98a1a3f2e0281c11a02d92d3fd",
    "    Same executionId? YES: replayed, not sent again",
    "[3] And this is what AgentKit cannot do:",
    "    the agent ASKS what actually happened.",
    "executionId: ok75dk43ushogcorut9i9",
    "status: completed",
    "Verified onchain result (1 receipt):",
    "  hash 0x0684e7df191193de1cc4684fe8a8d358f9daae98a1a3f2e0281c11a02d92d3fd | success | block 46890758 | gasUsed 67350 | verified 2026-09-16T09:10:04.669Z",
    "Conclusion: the transaction SUCCEEDED. Do not resend this work.",
    "explorer: https://sepolia.basescan.org/tx/0x0684e7df191193de1cc4684fe8a8d358f9daae98a1a3f2e0281c11a02d92d3fd"
  ],
  "part3": [
    "The agent asks for 50 USDC. The wallet holds about 4.",
    "Aborted before broadcast. Simulation predicts a revert: Error(ERC20: transfer amount exceeds balance). No transaction was sent and no gas was spent.",
    "    The simulation caught it. Zero transactions, zero gas."
  ],
  "summary": [
    "SUMMARY  AgentKit:  2 transfers for 1 job, outcome cannot be asked for.",
    "         KeeperHub: 1 transfer for 1 job, outcome verified onchain."
  ],
  "verify": [
    "> verify",
    "> for d in results/agentkit-*/; do echo \"$d\"; ./scripts/verify-receipts.sh \"$d/receipts.json\"; done",
    "results/agentkit-0.10.4/",
    "succeeded=315 reverted=0 not_found=0",
    "results/agentkit-0.9.1/",
    "succeeded=310 reverted=0 not_found=0"
  ],
  "test": [
    "> agentkit-keeperhub@0.1.2 test",
    "> npm run build && vitest run",
    "> agentkit-keeperhub@0.1.2 build",
    "> tsc -p tsconfig.json",
    " RUN  v2.1.9 /Users/scientivan/Programming/Ramz/Keeperhub/packages/agentkit-keeperhub",
    " ✓ test/keeperHubClient.test.ts (9 tests) 2ms",
    " ✓ test/keeperHubActionProvider.test.ts (13 tests) 5ms",
    " Test Files  2 passed (2)",
    "      Tests  22 passed (22)",
    "   Start at  18:42:45",
    "   Duration  3.52s (transform 47ms, setup 0ms, collect 6.60s, tests 7ms, environment 0ms, prepare 70ms)"
  ]
} as const;
