// Turns real captured runs into src/data/terminal.ts. Nothing is typed by hand:
//   ../harness/video/demo-transcript.json  ← scripts/record-demo.ts (npm run demo, timed)
//   public/terminal/verify.raw             ← npm run verify
//   public/terminal/test.raw               ← npm test
// The only edits: ANSI colour codes stripped, blank lines dropped, and one line removed from the
// demo, the [bootstrap] notice that the harness silenced an AgentKit analytics crash. It is a
// harness message, not part of what the agent sees.
import { readFileSync, writeFileSync } from "node:fs";

const clean = (s) => s.replace(/\x1b\[[0-9;]*m/g, "").split("\n").map((l) => l.replace(/\s+$/, "")).filter((l) => l.trim());

const demo = JSON.parse(readFileSync("../harness/video/demo-transcript.json", "utf8"));
const all = clean(demo.chunks.map((c) => c.text).join("")).filter((l) => !l.startsWith("[bootstrap]"));
const isRule = (l) => /^[=-]{20,}$/.test(l);

const idx = (re) => all.findIndex((l) => re.test(l));
const p1 = idx(/^PART 1/), p2 = idx(/^PART 2/), p3 = idx(/^PART 3/), sum = idx(/^SUMMARY/);
const part = (a, b) => all.slice(a + 1, b).filter((l) => !isRule(l));

const out = {
  recordedAt: demo.recordedAt,
  header: all.slice(0, p1).filter((l) => !isRule(l)),
  part1: part(p1, p2),
  part2: part(p2, p3),
  part3: part(p3, sum),
  summary: all.slice(sum).filter((l) => !isRule(l)),
  verify: clean(readFileSync("public/terminal/verify.raw", "utf8")).filter((l) => !/ total$|^(real|user|sys)\s/.test(l)),
  test: clean(readFileSync("public/terminal/test.raw", "utf8")).filter((l) => !/^found 0/.test(l)),
};

writeFileSync("src/data/terminal.ts",
  "// GENERATED by scripts/terminal-data.mjs from real captured runs. Do not edit by hand.\n" +
  `export const TERM = ${JSON.stringify(out, null, 2)} as const;\n`);
for (const [k, v] of Object.entries(out)) if (Array.isArray(v)) console.log(k.padEnd(8), v.length, "lines");
